// Generated by create-fsd-architecture. Re-run project configuration to update.
export const fsdStack = {
  framework: "nextjs",
  frameworkLabel: "Next.js",
  packageManager: "npm",
  apiClient: "axios",
  serverState: "react-query",
  clientState: "zustand",
  forms: "react-hook-form-zod",
  docsUrl: "https://fsd-docs.vercel.app",
  commands: {
    install: "npm install",
    dev: "npm run dev",
    build: "npm run build",
    generateFeature: "npx create-fsd-architecture@latest -g feature auth",
    generatePage: "npx create-fsd-architecture@latest -g page dashboard",
  },
} as const;
